name: test

on:
  push:
    branches:
      - master

jobs:
  build_macos:
    name: Build for MacOS
    runs-on: macOS-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: pypy3

      - name: Setup PIP
        run: pypy3 -m pip install --upgrade pip

      # - name: Setup Python cache
      #   uses: actions/cache@v2
      #   id: cache-python-cache
      #   with:
      #     path: ~/Library/Caches/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Install Python dependencies
        # if: steps.cache-python-cache.outputs.cache-hit != 'true'
        run: |
          pypy3 -m pip install -r requirements.txt
